version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'Europe/Rome'

    open-pull-requests-limit: 15
    versioning-strategy: 'increase-if-necessary'

    groups:
      non-major-all:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

      next-major:
        patterns:
          - 'next'
          - 'eslint-config-next'
        update-types:
          - 'major'

      react-major:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
        update-types:
          - 'major'

      tailwind-major:
        patterns:
          - 'tailwindcss'
          - 'autoprefixer'
          - 'postcss*'
        update-types:
          - 'major'

      typescript-major:
        patterns:
          - 'typescript'
          - '@types/node'
        update-types:
          - 'major'

      eslint-major:
        patterns:
          - 'eslint'
        update-types:
          - 'major'

      prettier-major:
        patterns:
          - 'prettier'
        update-types:
          - 'major'

      ui-libs-major:
        patterns:
          - 'react-icons'
        update-types:
          - 'major'

      other-majors:
        patterns:
          - '*'
        exclude-patterns:
          - 'next'
          - 'eslint-config-next'
          - 'react'
          - 'react-dom'
          - '@types/react'
          - 'tailwindcss'
          - 'autoprefixer'
          - 'postcss*'
          - 'typescript'
          - '@types/node'
          - 'eslint'
          - 'prettier'
          - 'react-icons'
        update-types:
          - 'major'

    labels:
      - 'dependencies'
      - 'dependabot'

    commit-message:
      prefix: 'deps'
      include: 'scope'
